Reach: 2
Energy costs:
- Green: 8
- Teal: 4
- Pink: 10
- Red: 0
Maximum energy: 10

Path:
-> Pink rock at (1, 3) (energy left: 0)
-> Rest (energy left: 10)
-> Pink rock at (3, 3) (energy left: 0)
-> Rest (energy left: 10)
-> Pink rock at (5, 3) (energy left: 0)
-> Rest (energy left: 10)
-> Pink rock at (7, 3) (energy left: 0)
-> Rest (energy left: 10)
-> Pink rock at (9, 3) (energy left: 0)

Total turns: 9
