#!/bin/bash

fn_name="dayTrip"
prog_name="testDayTrip"

set -o pipefail

cd "$(dirname "$0")"

echo "** Testing $fn_name"

make

if [ $? -ne 0 ]
then
	echo "compilation error: tests could not be run"
	exit 1
fi

for tin in tests/*.exp
do
	t="$(basename "$tin" .exp)"
	g="${t%-*}"
	v="${t#*-}"

	echo "------------------------------------"
	echo "** Test $t (./$prog_name tests/graph$g $v)"
	echo "------------------------------------"

	"./$prog_name" "tests/graph$g" "$v" | head -200 > "tests/$t.out" 

	if [ $? -ne 0 ]
	then
		echo
		echo "** Test failed (runtime error)"
		echo
	elif cmp -s "tests/$t.exp" "tests/$t.out"
	then
		echo "** Test passed"
	else
		echo "** Test failed (incorrect output)"
		echo
		echo "** Expected output (in tests/$t.exp):"
		cat "tests/$t.exp"
		echo
		echo "** Your output (in tests/$t.out):"
		if [ -s "tests/$t.out" ]
		then
			cat "tests/$t.out"
		else
			echo "(empty)"
		fi
		echo
	fi
done

echo
